Adding Advanced Wireless Setup Kit (#18)
* Added Advanced Wireless Setup Kit

* Update adv wireless setup kit texture

* Update adv wireless setup kit texture

* Added NBT Clearing recipe for adv wireless setup kit

* Added NBT clearing recipe for basic wireless kit and spotless

* Fixed issue where playing on a server could cause a NoSuchMethodError

* Added chat feedback for when mode is switched

* Spotless

* Added requested features from pull request review
 - Added constants to AdvWirelessKit.scala to define values for the modes
 - Added a constant to AdvItemLocationStore.scala to find the  NBTTag type and use that in place of  which was used previously
 - Added error logging to AdvWirelessKit.scala and ItemWirelessKit.scala for when a connection fails fatally
 - Switched else statements for mode to else if statements to explicitly check that the mode is the other mode

* Added requested features from pull request review
 - Added constants to AdvWirelessKit.scala to define values for the modes
 - Added a constant to AdvItemLocationStore.scala to find the COMPOUND NBTTag type and use that in place of 10 which was used previously
 - Added error logging to AdvWirelessKit.scala and ItemWirelessKit.scala for when a connection fails fatally
 - Switched else statements for mode to else if statements to explicitly check that the mode is the other mode